var device = [
    {
        "id":0,
        "name":"prime",
        "price":199,
        "texture":"prime.png",
        "options":["frontPanel","backPanel"],
    },
    {
        "id":1,
        "name":"tuff",
        "price":219,
        "texture":"tuff.png",
        "options":["frontPanel","backPanel"]
    },
    {
        "id":2,
        "name":"base",
        "price":49,
        "texture":"base.png",
        "options":["frontPanel"]
    }
];

var frontPanel = [
    {
        "id":0,
        "name":"Plastic",
        "price":0,
        "texture":"grey.png"
    },
    {
        "id":1,
        "name":"Black Plastic",
        "price":0,
        "texture":"black.png"
    },
    {
        "id":2,
        "name":"Aluminium",
        "price":2.99,
        "texture":"metalSilver.png"
    },
    {
        "id":3,
        "name":"Titanium",
        "price":2.99,
        "texture":"metalBlack.png"
    },
    {
        "id":4,
        "name":"Mahogony",
        "price":2.99,
        "texture":"waveRed.png"
    },
    {
        "id":5,
        "name":"Oak",
        "price":2.99,
        "texture":"woodDark.png"
    },
    {
        "id":6,
        "name":"Pine",
        "price":2.99,
        "texture":"woodYellow.png"
    }

];

var backPanel = [
    {
        "id":0,
        "name":"Plastic",
        "price":0,
        "texture":"grey.png"
    },
    {
        "id":1,
        "name":"Black Plastic",
        "price":0,
        "texture":"black.png"
    },
    {
        "id":2,
        "name":"Black Leather",
        "price":2.99,
        "texture":"leatherBlack.png"
    },
    {
        "id":3,
        "name":"Blue Leather",
        "price":2.99,
        "texture":"leatherBlue.png"
    },
    {
        "id":4,
        "name":"Red Leather",
        "price":2.99,
        "texture":"leatherRed.png"
    },
    {
        "id":5,
        "name":"Aluminium",
        "price":9.99,
        "texture":"metalSilver.png"
    },
    {
        "id":6,
        "name":"Titanium",
        "price":9.99,
        "texture":"metalBlack.png"
    },
    {
        "id":7,
        "name":"Maghogony",
        "price":4.99,
        "texture":"waveRed.png"
    },
    {
        "id":8,
        "name":"Oak",
        "price":4.99,
        "texture":"woodDark.png"
    },
    {
        "id":9,
        "name":"Pine",
        "price":4.99,
        "texture":"woodYellow.png"
    },
];